name: PHP CS Fixer

on:
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: cs2pr,php-cs-fixer

      - name: Get changed files
        id: changed_files
        run: |
          echo "::set-output name=files::$(git diff --name-only --diff-filter=AMR ${{ github.event.before }} ${{ github.sha }} | grep '\.php$')"

          - name: Run PHP CS Fixer
            run: |
              if [ -n "${{ steps.changed_files.outputs.files }}" ]; then
                echo "Running PHP CS Fixer on changed files..."
                echo "${{ steps.changed_files.outputs.files }}" | xargs -n 1 php-cs-fixer fix --dry-run --diff --verbose
              else
                echo "No PHP files changed."
              fi

#      - name: Run PHP CS Fixer
#        if: env.files != ''
#        run: php-cs-fixer fix $files --dry-run --diff --rules=@PER-CS2.0 --format=checkstyle | cs2pr
