name: PHP CS Fixer

on:
  push:
    branches:
      - "8.0"
      - "8.0-CONTRIBUTING"
    paths:
      - '**.php'
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer,cs2pr,php-cs-fixer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Fetch all branches
        run: git fetch --all

      - name: Get list of modified files
        id: modified_files
        run: |
          IFS=$'\n'
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php-cs-fixer(\\.dist)?\\.php|composer\\.lock)$"; then EXTRA_ARGS=$(printf -- '--path-mode=intersection\n--\n%s' "${CHANGED_FILES}"); else EXTRA_ARGS=''; fi
          vendor/bin/php-cs-fixer check --config=.php-cs-fixer.dist.php -v --stop-on-violation --using-cache=no ${EXTRA_ARGS}

      - name: Run PHP CS Fixer
        if: env.files != ''
        run: php-cs-fixer fix $files --dry-run --diff --rules=@PER-CS2.0 --format=checkstyle | cs2pr
